//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusStory.База_данных
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BaseModelFocusEntities6 : DbContext
    {
        private static BaseModelFocusEntities6 _context;
        public BaseModelFocusEntities6()
            : base("name=BaseModelFocusEntities6")
        {
        }

        public static BaseModelFocusEntities6 GetContext()
        {
            if (_context == null)
                _context = new BaseModelFocusEntities6();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
