//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusStory.База_данных
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int idClient { get; set; }
        public string nameClient { get; set; }
        public string surnameClient { get; set; }
        public string patronymicClient { get; set; }
        public Nullable<long> phoneNumber { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> idBasket { get; set; }
    
        public virtual Basket Basket { get; set; }
    }
}
